# Generated by Django 2.2.5 on 2020-08-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Food Type',
            },
        ),
        migrations.RenameModel(
            old_name='Photo',
            new_name='FoodPhoto',
        ),
        migrations.AddField(
            model_name='food',
            name='food_type',
            field=models.ManyToManyField(blank=True, to='foods.FoodType'),
        ),
    ]
