# Generated by Django 2.2.5 on 2020-08-29 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_auto_20200830_0206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodtype',
            options={},
        ),
    ]
