# Generated by Django 2.2.5 on 2020-08-29 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_auto_20200830_0210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodtype',
            options={'verbose_name': 'Food Type'},
        ),
    ]
