# Generated by Django 2.2.5 on 2020-08-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_auto_20200830_0214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='name',
        ),
        migrations.RemoveField(
            model_name='food',
            name='price',
        ),
        migrations.AddField(
            model_name='food',
            name='food_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='food',
            name='food_store',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.RemoveField(
            model_name='food',
            name='food_type',
        ),
        migrations.AddField(
            model_name='food',
            name='food_type',
            field=models.CharField(blank=True, choices=[('한식', '한식'), ('일식', '일식'), ('양식', '양식')], max_length=10),
        ),
    ]
