# Generated by Django 2.2.5 on 2020-08-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_auto_20200830_0235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='food_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='food_store',
            new_name='store',
        ),
        migrations.RemoveField(
            model_name='food',
            name='food_type',
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.CharField(blank=True, choices=[('한식', '한식'), ('일식', '일식'), ('양식', '양식'), ('중식', '중식')], max_length=20),
        ),
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
