# Generated by Django 2.2.5 on 2020-08-29 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0006_auto_20200830_0320'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodType',
            new_name='FoodCategory',
        ),
        migrations.AlterModelOptions(
            name='foodcategory',
            options={'verbose_name': 'Food Category'},
        ),
    ]
