# Generated by Django 2.2.5 on 2020-08-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_login_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('Email', 'Email'), ('Github', 'Github'), ('Kakao', 'Kakao')], default='Email', max_length=50),
        ),
    ]
