# Generated by Django 2.2.5 on 2020-08-21 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200816_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avata',
            new_name='avatar',
        ),
    ]
