# Generated by Django 2.2.5 on 2020-08-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200821_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, choices=[('서울', '서울'), ('통영', '통영'), ('부산', '부산')], max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='currency',
            field=models.CharField(blank=True, choices=[('원화', '원화'), ('상품권', '상품권')], default='원화', max_length=3),
        ),
    ]
