# Generated by Django 2.2.5 on 2020-07-27 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20200727_2123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='contry',
            new_name='country',
        ),
    ]
