# Generated by Django 2.2.5 on 2020-08-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0008_auto_20200807_1413"),
    ]

    operations = [
        migrations.RenameField(model_name="room", old_name="bath", new_name="baths",),
        migrations.RenameField(
            model_name="room", old_name="facility", new_name="facilities",
        ),
        migrations.RenameField(
            model_name="room", old_name="house_rule", new_name="house_rules",
        ),
        migrations.AlterField(
            model_name="room",
            name="guests",
            field=models.IntegerField(help_text="How many people will be staying?"),
        ),
    ]
