# Generated by Django 2.2.5 on 2020-08-28 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_auto_20200811_2037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ('-created',)},
        ),
    ]
