# Generated by Django 2.2.5 on 2020-08-29 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_auto_20200829_0229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ('-created',)},
        ),
    ]
