# Generated by Django 2.2.5 on 2020-08-29 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_auto_20200830_0000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={},
        ),
    ]
