# Generated by Django 2.2.5 on 2020-08-30 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0012_auto_20200830_0001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={},
        ),
    ]
