# Generated by Django 2.2.5 on 2020-08-31 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dinings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='food',
            new_name='dining',
        ),
    ]
